#!/bin/bash

# 폴더 경로를 입력받습니다.
read -p "폴더 경로를 입력하세요: " directory

# 이동할 디렉토리를 입력받습니다.
#read -p "이동할 디렉토리를 입력하세요: " destination_directory

# 폴더 내의 파일명을 추출합니다.
file_list=$(ls "$directory")

mkdir "$directory/server1"
mkdir "$directory/server2"

# 추출한 파일들을 순회하며 이동합니다.
for file in $file_list
do
	#echo "$file"
	extension="${file##*.}"
	#echo "$extension"
	if [ "$extension" = "xml" ]||[ "$extension" = "qcow2" ]; then
		extracted_string=${file:0:6}
		#echo "추출된 문자열: $extracted_string"
		count=$((extracted_string%2))
	#	echo "$count"
		if [ $count -eq 1 ]; then
			cp "$file" "/home/test/server1"
			#echo "파일 $file 를 $destination_directory 로 이동했습니다."
		elif [ $count -eq 0 ]; then
			cp "$file" "/home/test/server2"
			#echo "파일 $file 를 $destination_directory 로 이동했습니다."
		fi
	fi
done


default-example-service-39fa4-23407250-d492ab39ad0d.kr.lb.naverncp.com 
